spring.application.name=backend

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/studyflow
spring.datasource.username=postgres
spring.datasource.password=Estefaniapi12

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=studyflow_super_secret_key_2024_muito_longa_e_segura_para_funcionar
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG